"""Add spotlight and bookmark to submissions

Revision ID: 010b930cda3b
Revises: b8bece5ea4fa
Create Date: 2025-10-24 21:45:05.318737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010b930cda3b'
down_revision: Union[str, Sequence[str], None] = 'b8bece5ea4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('played_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_spotlighted', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('is_bookmarked', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('is_bookmarked')
        batch_op.drop_column('is_spotlighted')
        batch_op.drop_column('played_at')

    # ### end Alembic commands ###
