"""Rename artist and title to track_artist and track_title

Revision ID: 0f8deafed2c5
Revises: 52080e6f9a8d
Create Date: 2025-10-30 12:41:56.883713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8deafed2c5'
down_revision: Union[str, Sequence[str], None] = '52080e6f9a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_artist', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('track_title', sa.String(), nullable=True))
        batch_op.drop_column('artist')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('artist', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('track_title')
        batch_op.drop_column('track_artist')

    # ### end Alembic commands ###
