"""add_see_the_line_channel_id

Revision ID: 17902fdc8faf
Revises: add_tiktok_stats
Create Date: 2025-11-25 10:50:06.609772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17902fdc8faf'
down_revision: Union[str, Sequence[str], None] = 'add_tiktok_stats'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_sessions_id'), ['id'], unique=False)

    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('see_the_line_channel_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['see_the_line_channel_id'])

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_achievement'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_achievement'), ['user_id', 'achievement_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('see_the_line_channel_id')

    with op.batch_alter_table('live_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_sessions_id'))

    # ### end Alembic commands ###
