"""Add files and links channel to reviewer

Revision ID: 184d4311d8c9
Revises: 010b930cda3b
Create Date: 2025-10-25 00:22:57.374718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184d4311d8c9'
down_revision: Union[str, Sequence[str], None] = '010b930cda3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('files_and_links_channel_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint("uq_files_and_links_channel_id", ['files_and_links_channel_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('files_and_links_channel_id')

    # ### end Alembic commands ###
