"""add_pending_coins

Revision ID: 205f668e3173
Revises: add_global_config
Create Date: 2025-12-02 21:05:03.078557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205f668e3173'
down_revision: Union[str, Sequence[str], None] = 'add_global_config'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_configs_key'), ['key'], unique=False)

    with op.batch_alter_table('tiktok_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_coins', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_accounts', schema=None) as batch_op:
        batch_op.drop_column('pending_coins')

    with op.batch_alter_table('global_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_configs_key'))

    # ### end Alembic commands ###
