"""add_platform_revenue_usd

Revision ID: 33dbbd4bdc91
Revises: 8a78d2c90ff8
Create Date: 2025-12-03 22:47:47.102733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dbbd4bdc91'
down_revision: Union[str, Sequence[str], None] = '8a78d2c90ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_revenue_usd', sa.Numeric(precision=10, scale=4), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_ledger', schema=None) as batch_op:
        batch_op.drop_column('platform_revenue_usd')

    # ### end Alembic commands ###
