"""Add review session table and link to submissions

Revision ID: 3e191648502a
Revises: 80d3eb9130da
Create Date: 2025-11-06 05:11:21.899136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy.orm import Session
from models import JsonEncodedList # Import the custom type

# revision identifiers, used by Alembic.
revision: str = '3e191648502a'
down_revision: Union[str, Sequence[str], None] = '80d3eb9130da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and perform data migration."""
    # ### Schema migration ###
    review_sessions_table = op.create_table('review_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reviewer_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('open_queue_tiers', JsonEncodedList(), nullable=False),
        sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_sessions_reviewer_id'), ['reviewer_id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skip_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_submissions_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key('fk_submissions_session_id', 'review_sessions', ['session_id'], ['id'])


    # ### Data migration ###
    bind = op.get_bind()
    session = Session(bind=bind)

    # Define table structures for query building
    reviewers = table('reviewers', column('id', sa.Integer))
    submissions = table('submissions',
                        column('id', sa.Integer),
                        column('reviewer_id', sa.Integer),
                        column('session_id', sa.Integer)
                       )

    # Get all existing reviewers
    reviewer_list = session.execute(sa.select(reviewers.c.id)).fetchall()

    if not reviewer_list:
        print("No reviewers found, skipping data migration.")
        return

    # Create a default session for each reviewer and associate submissions
    for reviewer_id_tuple in reviewer_list:
        reviewer_id = reviewer_id_tuple[0]

        # Create the "Default Session"
        default_session_insert = review_sessions_table.insert().values(
            name='Default Session',
            status='archived',
            reviewer_id=reviewer_id,
            open_queue_tiers=[0, 5, 10, 15, 20, 25] # Default value
        )
        result = session.execute(default_session_insert)
        session.commit()

        # The inserted_primary_key is a list, get the first element
        new_session_id = result.inserted_primary_key[0]

        # Update existing submissions for this reviewer to point to the new session
        session.execute(
            sa.update(submissions)
            .where(submissions.c.reviewer_id == reviewer_id)
            .values(session_id=new_session_id)
        )
        session.commit()

    print(f"Data migration complete. Created default sessions for {len(reviewer_list)} reviewers.")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_submissions_session_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_submissions_session_id'))
        batch_op.drop_column('skip_count')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_sessions_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_review_sessions_id'))

    op.drop_table('review_sessions')
    # ### end Alembic commands ###
