"""Add spotify tokens to user model

Revision ID: 5223aef398a5
Revises: f657320e6a35
Create Date: 2025-11-11 06:02:21.046418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5223aef398a5'
down_revision: Union[str, Sequence[str], None] = 'f657320e6a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_access_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('spotify_refresh_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('spotify_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('spotify_token_expires_at')
        batch_op.drop_column('spotify_refresh_token')
        batch_op.drop_column('spotify_access_token')

    # ### end Alembic commands ###
