"""add discord user cache

Revision ID: 67bcd1c4a5ae
Revises: 85b8ec43a134
Create Date: 2025-11-03 19:51:10.312672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bcd1c4a5ae'
down_revision: Union[str, Sequence[str], None] = '85b8ec43a134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_user_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discord_user_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discord_user_cache_discord_id'), ['discord_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_discord_user_cache_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discord_user_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discord_user_cache_id'))
        batch_op.drop_index(batch_op.f('ix_discord_user_cache_discord_id'))

    op.drop_table('discord_user_cache')
    # ### end Alembic commands ###
