"""Add ReviewSession and link to Submission

Revision ID: 79489dd5828d
Revises: 80d3eb9130da
Create Date: 2025-11-05 20:30:59.599687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79489dd5828d'
down_revision: Union[str, Sequence[str], None] = '80d3eb9130da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    review_sessions_table = op.create_table('review_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reviewer_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('open_queue_tiers', postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_sessions_reviewer_id'), ['reviewer_id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_submissions_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key('fk_submission_session', 'review_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###

    # Custom data migration
    bind = op.get_bind()
    reviewers_table = sa.Table('reviewers', sa.MetaData(), sa.Column('id', sa.Integer, primary_key=True))
    submissions_table = sa.Table('submissions', sa.MetaData(), sa.Column('id', sa.Integer, primary_key=True), sa.Column('reviewer_id', sa.Integer), sa.Column('session_id', sa.Integer))

    reviewers = bind.execute(sa.select(reviewers_table.c.id)).fetchall()

    for reviewer in reviewers:
        reviewer_id = reviewer[0]
        # Create a default session for the reviewer
        result = bind.execute(review_sessions_table.insert().values(
            reviewer_id=reviewer_id,
            name='Default Session',
            status='archived'
        ).returning(review_sessions_table.c.id))
        session_id = result.fetchone()[0]

        # Update existing submissions for the reviewer to point to the new session
        bind.execute(
            submissions_table.update().
            where(submissions_table.c.reviewer_id == reviewer_id).
            values(session_id=session_id)
        )

    # Make the session_id column non-nullable after migration
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('session_id', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_submission_session', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_submissions_session_id'))
        batch_op.drop_column('session_id')

    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_sessions_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_review_sessions_id'))

    op.drop_table('review_sessions')
    # ### end Alembic commands ###
