"""Add queue_status to Reviewer

Revision ID: 7e3690a64577
Revises: 7cffd9744e53
Create Date: 2025-10-22 16:00:07.510417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3690a64577'
down_revision: Union[str, Sequence[str], None] = '7cffd9744e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewers', sa.Column('queue_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviewers', 'queue_status')
    # ### end Alembic commands ###
