"""Add reviewer avatar and bio

Revision ID: 7e401dc950bb
Revises: d942106c20c4
Create Date: 2025-11-23 06:15:43.752856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e401dc950bb'
down_revision: Union[str, Sequence[str], None] = 'd942106c20c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists to avoid DuplicateTableError
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    if 'payment_configs' not in tables:
        op.create_table('payment_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reviewer_id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('credentials', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('payment_configs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_payment_configs_id'), ['id'], unique=False)

    # Check columns for reviewers table
    columns = [c['name'] for c in inspector.get_columns('reviewers')]

    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        if 'avatar_url' not in columns:
            batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))
        if 'bio' not in columns:
            batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('payment_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_configs_id'))

    op.drop_table('payment_configs')
    # ### end Alembic commands ###
