"""Add reviewer avatar and bio

Revision ID: 7e401dc950bb
Revises: d942106c20c4
Create Date: 2025-11-23 06:15:43.752856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import logging

# revision identifiers, used by Alembic.
revision: str = '7e401dc950bb'
down_revision: Union[str, Sequence[str], None] = 'd942106c20c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists to avoid DuplicateTableError
    # Using try/except as inspect can be unreliable in some async/docker contexts
    try:
        op.create_table('payment_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reviewer_id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('credentials', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('payment_configs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_payment_configs_id'), ['id'], unique=False)
    except Exception as e:
        # Likely DuplicateTableError, safe to ignore if table exists
        print(f"Skipping payment_configs table creation: {e}")

    # Check columns for reviewers table
    # For columns, we can use specific add_column commands wrapped in checks or try/except
    # But here we really want to know if column exists.
    # Inspect for columns usually works better or we can try adding and ignore error.
    try:
        with op.batch_alter_table('reviewers', schema=None) as batch_op:
            batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))
    except Exception:
        pass

    try:
        with op.batch_alter_table('reviewers', schema=None) as batch_op:
            batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
    except Exception:
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('payment_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_configs_id'))

    op.drop_table('payment_configs')
    # ### end Alembic commands ###
