"""Add fields to Submission model

Revision ID: 80d3eb9130da
Revises: dd38288aeeba
Create Date: 2025-11-04 22:09:31.661026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d3eb9130da'
down_revision: Union[str, Sequence[str], None] = 'dd38288aeeba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('archived_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('score')
        batch_op.drop_column('archived_url')
        batch_op.drop_column('track_title')

    # ### end Alembic commands ###
