"""add_dual_currency_models

Revision ID: 8a78d2c90ff8
Revises: d8e3d47e70ae
Create Date: 2025-12-03 22:29:22.777780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a78d2c90ff8'
down_revision: Union[str, Sequence[str], None] = 'd8e3d47e70ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('balance_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_earnings_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reviewer_id')
    )
    with op.batch_alter_table('reviewer_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewer_wallets_id'), ['id'], unique=False)

    op.create_table('transaction_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('credits_spent', sa.Integer(), nullable=False),
    sa.Column('usd_earned', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('exchange_rate_snapshot', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_ledger_id'), ['id'], unique=False)

    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_price_credits', sa.Integer(), nullable=False, server_default='100'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_balance', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('credit_balance')

    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.drop_column('skip_price_credits')

    with op.batch_alter_table('transaction_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_ledger_id'))

    op.drop_table('transaction_ledger')
    with op.batch_alter_table('reviewer_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewer_wallets_id'))

    op.drop_table('reviewer_wallets')
    # ### end Alembic commands ###
