"""Add review fields to Submission model

Revision ID: 8ab7d909de1f
Revises: 0f8deafed2c5
Create Date: 2025-11-01 05:46:26.272070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab7d909de1f'
down_revision: Union[str, Sequence[str], None] = '0f8deafed2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('private_notes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('public_review', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('public_review')
        batch_op.drop_column('private_notes')
        batch_op.drop_column('tags')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
