"""add_bookmark_and_spotlight_to_submission

Revision ID: a1b2c3d4e5f6
Revises: 3e191648502a
Create Date: 2025-11-19 09:22:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '3e191648502a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('bookmarked', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('submissions', sa.Column('spotlighted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'spotlighted')
    op.drop_column('submissions', 'bookmarked')
    # ### end Alembic commands ###
