"""Enhance submission model

Revision ID: aebadb9569a7
Revises: 184d4311d8c9
Create Date: 2025-10-27 14:23:34.147777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebadb9569a7'
down_revision: Union[str, Sequence[str], None] = '184d4311d8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_reviewers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_reviewers_id'), ['id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('submission_count', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('submission_count')
        batch_op.drop_column('title')
        batch_op.drop_column('artist')

    with op.batch_alter_table('submission_reviewers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_reviewers_id'))

    op.drop_table('submission_reviewers')
    # ### end Alembic commands ###
