"""Add moderator and update reviewer models

Revision ID: b8bece5ea4fa
Revises: 85b8ec43a134
Create Date: 2025-10-24 04:32:09.122655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bece5ea4fa'
down_revision: Union[str, Sequence[str], None] = '85b8ec43a134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderators_id'), ['id'], unique=False)

    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_channel_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('queue_channel_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('reviewer_role_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['reviewer_role_id'])
        batch_op.create_unique_constraint(None, ['queue_channel_id'])
        batch_op.create_unique_constraint(None, ['submission_channel_id'])
        batch_op.drop_column('discord_channel_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_channel_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reviewer_role_id')
        batch_op.drop_column('queue_channel_id')
        batch_op.drop_column('submission_channel_id')

    with op.batch_alter_table('moderators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderators_id'))

    op.drop_table('moderators')
    # ### end Alembic commands ###
