"""add_community_goal_cooldown

Revision ID: d8e3d47e70ae
Revises: 205f668e3173
Create Date: 2025-12-02 21:36:15.376760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e3d47e70ae'
down_revision: Union[str, Sequence[str], None] = '205f668e3173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
"""add_community_goal_cooldown

Revision ID: d8e3d47e70ae
Revises: 205f668e3173
Create Date: 2025-12-02 21:36:15.376760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e3d47e70ae'
down_revision: Union[str, Sequence[str], None] = '205f668e3173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_goal_cooldown_minutes', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.drop_column('community_goal_cooldown_minutes')

    # ### end Alembic commands ###
