"""add_tiktok_tables

Revision ID: d942106c20c4
Revises: merge_heads
Create Date: 2025-11-22 03:58:29.792202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd942106c20c4'
down_revision: Union[str, Sequence[str], None] = 'merge_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiktok_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tiktok_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tiktok_accounts_handle_name'), ['handle_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tiktok_accounts_id'), ['id'], unique=False)

    op.create_table('tiktok_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('tiktok_account_id', sa.Integer(), nullable=True),
    sa.Column('host_handle', sa.String(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('coin_value', sa.Integer(), nullable=True),
    sa.Column('user_level', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ),
    sa.ForeignKeyConstraint(['tiktok_account_id'], ['tiktok_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tiktok_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tiktok_interactions_id'), ['id'], unique=False)

    op.create_table('tiktok_rank_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('tiktok_user_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['review_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tiktok_rank_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tiktok_rank_updates_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_rank_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tiktok_rank_updates_id'))

    op.drop_table('tiktok_rank_updates')
    with op.batch_alter_table('tiktok_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tiktok_interactions_id'))

    op.drop_table('tiktok_interactions')
    with op.batch_alter_table('tiktok_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tiktok_accounts_id'))
        batch_op.drop_index(batch_op.f('ix_tiktok_accounts_handle_name'))

    op.drop_table('tiktok_accounts')
    # ### end Alembic commands ###
