"""Make discord_channel_id nullable

Revision ID: dd38288aeeba
Revises: fb592927c4cd
Create Date: 2025-11-03 23:31:29.840689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd38288aeeba'
down_revision: Union[str, Sequence[str], None] = 'fb592927c4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.alter_column('discord_channel_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.alter_column('discord_channel_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
