"""Add ReviewSession model

Revision ID: f657320e6a35
Revises: 3e191648502a
Create Date: 2025-11-08 23:17:01.879753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f657320e6a35'
down_revision: Union[str, Sequence[str], None] = '3e191648502a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_review_sessions_reviewer_id'))
        batch_op.drop_column('open_queue_tiers')
        batch_op.drop_column('status')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_session_id'))
        batch_op.drop_column('skip_count')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_count', sa.INTEGER(), nullable=True))
        batch_op.create_index(batch_op.f('ix_submissions_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('open_queue_tiers', sa.TEXT(), nullable=False))
        batch_op.create_index(batch_op.f('ix_review_sessions_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
