"""make discord_channel_id nullable

Revision ID: fb592927c4cd
Revises: 67bcd1c4a5ae
Create Date: 2025-11-03 19:52:48.557298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb592927c4cd'
down_revision: Union[str, Sequence[str], None] = '67bcd1c4a5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
