"""Add smart zone fields

Revision ID: smart_zone_fields
Revises: f657320e6a35, e5f6g7h8i9j0
Create Date: 2025-11-21 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'smart_zone_fields'
down_revision: Union[str, Sequence[str], None] = ('f657320e6a35', 'e5f6g7h8i9j0')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: is_priority was added in e5f6g7h8i9j0, so we don't need to add it here.

    op.add_column('submissions', sa.Column('batch_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_submissions_batch_id'), 'submissions', ['batch_id'], unique=False)
    op.add_column('submissions', sa.Column('sequence_order', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('submissions', sa.Column('hook_start_time', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('hook_end_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'hook_end_time')
    op.drop_column('submissions', 'hook_start_time')
    op.drop_column('submissions', 'sequence_order')
    op.drop_index(op.f('ix_submissions_batch_id'), table_name='submissions')
    op.drop_column('submissions', 'batch_id')
    # ### end Alembic commands ###
